apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy
  name: AppService
  namespace: default
spec:
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy
  type: NodePort
